### ISSUE TITLE
上传文件报413 Request Entity Too Large 是nginx被限制了么 我看nginx配置文件是OK的 是没有挂载对应的nginx配置文件

### ISSUE THREAD

**Issue by thb-club** [lihuacai168/AnotherFasterRunner#101]
**描述问题**
清晰明确地描述这个问题是什么。

**重现步骤**
重现行为的步骤：
1. 前往“...”
2. 点击“...”
3. 向下滚动至“...”
4. 查看错误

**期望的行为**
清晰明确地描述你期望发生的事情。

**截图**
如果适用的话，添加截图以帮助解释你的问题。

**版本和代码（请填写以下信息）：**
- 操作系统：[例如MacOs 13, Win10]
- 浏览器：[例如Chrome、Safari]
- 代码版本：[例如V2.2.1，最新的代码哈希值]
- Python版本: [Python3.9]

**其他相关信息**
在此处添加任何与问题有关的其他上下文信息。

**Comment by lihuacai168** [comment]
请认真描述BUG
上传文件接口，目前项目是没实现的
