### ISSUE TITLE
环境搭建-极速启动报错：celery-worker、celery-beat下载失败

### ISSUE THREAD

**Issue by wangyunshuai** [lihuacai168/AnotherFasterRunner#112]
celery-worker、celery-beat两个镜像下载失败，其他镜像下载成功

docker-compose -f docker-compose-for-fastup.yml --env-file .env.example up -d

Pulling celery-worker (rikasai/fast-runner-backend:latest)...
latest: Pulling from rikasai/fast-runner-backend
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

Mac 系统，M1 处理器
系统版本：13.0.1 (22A400)
docker 版本
<img width="760" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/12732404/1405c18d-42d9-48ed-9402-baafe0762947">

**Comment by lihuacai168** [comment]
已经增加arm版镜像，请重试，如果运行成功，麻烦关闭issue
https://hub.docker.com/layers/rikasai/fast-runner-backend/latest/images/sha256-ea8fbe9a048155e2ff5e5eee067fd4aa985d76b4e1defd712a23aa972a2e9612?context=repo

**Comment by wangyunshuai** [comment]
> 已经增加arm版镜像，请重试，如果运行成功，麻烦关闭issue https://hub.docker.com/layers/rikasai/fast-runner-backend/latest/images/sha256-ea8fbe9a048155e2ff5e5eee067fd4aa985d76b4e1defd712a23aa972a2e9612?context=repo @wangyunshuai

上面两个已经可以了，另外出现了这个，也需要适配下 arm 版镜像，谢谢
Pulling web (rikasai/fast-runner-frontend:latest)...
latest: Pulling from rikasai/fast-runner-frontend
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by lihuacai168** [comment]
> > 已经增加arm版镜像，请重试，如果运行成功，麻烦关闭issue https://hub.docker.com/layers/rikasai/fast-runner-backend/latest/images/sha256-ea8fbe9a048155e2ff5e5eee067fd4aa985d76b4e1defd712a23aa972a2e9612?context=repo @wangyunshuai
> 
> 上面两个已经可以了，另外出现了这个，也需要适配下 arm 版镜像，谢谢 Pulling web (rikasai/fast-runner-frontend:latest)... latest: Pulling from rikasai/fast-runner-frontend ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

#114 已经增加前端镜像支持arm

**Comment by lihuacai168** [comment]
> > > 已经增加arm版镜像，请重试，如果运行成功，麻烦关闭issue https://hub.docker.com/layers/rikasai/fast-runner-backend/latest/images/sha256-ea8fbe9a048155e2ff5e5eee067fd4aa985d76b4e1defd712a23aa972a2e9612?context=repo @wangyunshuai
> > 
> > 
> > 上面两个已经可以了，另外出现了这个，也需要适配下 arm 版镜像，谢谢 Pulling web (rikasai/fast-runner-frontend:latest)... latest: Pulling from rikasai/fast-runner-frontend ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
> 
> #114 已经增加前端镜像支持arm

前端增加arm版镜像，一直是构建失败，晚点看看

**Comment by lihuacai168** [comment]
> #113 已经增加后端arm版镜像，请重试，如果运行成功，麻烦关闭issue https://hub.docker.com/layers/rikasai/fast-runner-backend/latest/images/sha256-ea8fbe9a048155e2ff5e5eee067fd4aa985d76b4e1defd712a23aa972a2e9612?context=repo @wangyunshuai

非常抱歉，因为加入了arm架构支持，导致ci构建镜像超过10min，并且前端也无法同时支持arm，所以把后端对arm架构的支持也取消掉。
等到前后端同时支持了再加回来
