### ISSUE TITLE
无法异步执行用例

### ISSUE THREAD

**Issue by monyuan** [lihuacai168/AnotherFasterRunner#12]
异步执行接口可以调用成功，但实际没执行，也没有任何报错

**Comment by monyuan** [comment]
文档少写了还要跑一个异步任务
代码也有点问题，跑异步任务的时候，无法发现task，需要在fastrunner里的init文件里注册app

from FasterRunner.mycelery import app

__all__ = ['app']

**Comment by lihuacai168** [comment]
> 文档少写了还要跑一个异步任务 代码也有点问题，跑异步任务的时候，无法发现task，需要在fastrunner里的init文件里注册app
> 
> from FasterRunner.mycelery import app
> 
> **all** = ['app']

task是自动发现的
异步任务只不过是apply调用一下那个任务而已

如果没跑，请发一下worker和beat的日志
