### ISSUE TITLE
Ubuntu  docker极速启动安装报错 mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json'

### ISSUE THREAD

**Issue by wangyunshuai** [lihuacai168/AnotherFasterRunner#121]
➜  ~ uname -a
Linux 10-42-35-55 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

➜  ~ docker -v
Docker version 19.03.2, build 6a30dfc

➜  ~ docker-compose -v
Docker Compose version v2.22.0

➜  AnotherFasterRunner git:(master) docker-compose -f docker-compose-for-fastup.yml --env-file .env.example up -d
WARN[0000] The "DJANGO_API_PORT" variable is not set. Defaulting to a blank string.
[+] Running 11/15
 ✘ app Error                                                                                                                                                           24.3s
 ⠸ celery-worker Pulling                                                                                                                                               24.3s
 ✘ db Error                                                                                                                                                            24.3s
 ✘ celery-beat Error                                                                                                                                                   24.3s
 ⠸ mq 10 layers [⣿⣿⣦⣿⣿⣿⣿⣿⣿⣦] 42.57MB/60.57MB Pulling                                                                                                                   24.3s
   ✔ 59bf1c3509f3 Pull complete                                                                                                                                         3.2s
   ✔ 237f3abe70c8 Pull complete                                                                                                                                         3.1s
   ⠦ 3d5e7f7d5ed8 Downloading   [===================================>               ]   32.4MB/46.16MB                                                                  6.6s
   ✔ 2c1c04e3aa30 Download complete                                                                                                                                     3.7s
   ✔ 02de786484eb Download complete                                                                                                                                     4.7s
   ✔ d1ddf3fc8b04 Download complete                                                                                                                                     4.4s
   ✔ 719f7f016b93 Download complete                                                                                                                                     4.9s
   ✔ c5c3324bd07e Download complete                                                                                                                                     5.3s
   ✔ 1854abf7e63e Download complete                                                                                                                                     5.4s
   ⠦ 544b62e61147 Downloading   [===================================>               ]  10.17MB/14.41MB                                                                  6.6s
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

**Comment by lihuacai168** [comment]
这个是演示demo上的版本，可以参考一下
```shell
# root @ VM-20-16-centos in ~/code/Jmeter-Toolkit on git:master o [14:21:18]
$ docker -v
Docker version 20.10.5, build 55c4c88
You have new mail.

# root @ VM-20-16-centos in ~/code/Jmeter-Toolkit on git:master o [14:21:21]
$ docker-compose --version
Docker Compose version v2.17.2
```

**Comment by wangyunshuai** [comment]
docker 版本更新后可以了
