### ISSUE TITLE
导入 yapi 接口数据时，post 请求中的 body 参数没有导入进来

### ISSUE THREAD

**Issue by wangyunshuai** [lihuacai168/AnotherFasterRunner#129]
导入 yapi 接口数据时，post 请求中的 body 参数没有导入进来

**Comment by lihuacai168** [comment]
> 导入 yapi 接口数据时，post 请求中的 body 参数没有导入进来

yapi版本提供一下

**Comment by wangyunshuai** [comment]
查看了源代码，没有处理 Body 的部分，不支持导入此内容
