### ISSUE TITLE
请教一个问题：参数化，为什么要放到配置管理里面而不是放到用例下面，是有什么考量吗？

### ISSUE THREAD

**Issue by wangyunshuai** [lihuacai168/AnotherFasterRunner#130]
![image](https://github.com/lihuacai168/AnotherFasterRunner/assets/12732404/185862df-2d49-4b3c-b34c-175aaaa0fc18)

**Comment by lihuacai168** [comment]
历史原因，httprunner设计之初就是这样了

**Comment by wangyunshuai** [comment]
谢谢
