### ISSUE TITLE
如果 1 条用例中包含了不同域名的接口，域名的 IP 地址也是不一样的，是不是不支持的？

### ISSUE THREAD

**Issue by wangyunshuai** [lihuacai168/AnotherFasterRunner#132]
如果 1 条用例中包含了不同域名的接口，域名的 IP 地址也是不一样的，是不是不支持的？

**Comment by lihuacai168** [comment]
参考在线demo的用例“登录-mock”
http://119.91.147.215/fastrunner/login

在配置中设置域名变量，然后在base_url中变量即可
<img width="2516" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/11568297/b35b6ad3-957a-4144-93e0-5c23e8ecd5e1">
