### ISSUE TITLE
makemigrations提示The SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by navy1997** [lihuacai168/AnotherFasterRunner#2]
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by navy1997** [comment]
pip install 依赖后
使用django数据库迁移命令 python manage.py makemigrations
提示error：django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by lihuacai168** [comment]
参考部署文档，`makemigrations`需要指定配置文件
https://www.yuque.com/lihuacai/sggdx7/toq6z9
![image](https://user-images.githubusercontent.com/11568297/105273773-e5b67100-5bd6-11eb-886a-fed44f133840.png)
