### ISSUE TITLE
CSRF验证失败. 请求被中断.

### ISSUE THREAD

**Issue by zhergd** [lihuacai168/AnotherFasterRunner#226]
<img width="401" alt="企业微信20241108-165748@2x" src="https://github.com/user-attachments/assets/d34078ce-39a8-49d3-ab88-8f16cfd714ff">

使用 docker compose 部署后登录 Django后报错

禁止访问 (403)
CSRF验证失败. 请求被中断.

请问有遇到同样的问题吗

**Comment by lihuacai168** [comment]
请提供更多的信息，登录地址，后端日志，f12请求内容

**Comment by zhergd** [comment]
> 请提供更多的信息，登录地址，后端日志，f12请求内容

地址：xxx:8000/admin/login

log：2024-11-10 10:02:52,457 [2ed92624554245c0833478127d392ebb] django.security.csrf WARNING [pid:9] [log.py->log_response:241] Forbidden (Origin checking failed - http://43.167.223.118:8000 does not match any trusted origins.): /admin/login/

**Comment by zhergd** [comment]
> > 请提供更多的信息，登录地址，后端日志，f12请求内容
> 
> 地址：xxx:8000/admin/login
> 
> log：2024-11-10 10:02:52,457 [2ed92624554245c0833478127d392ebb] django.security.csrf WARNING [pid:9] [log.py->log_response:241] Forbidden (Origin checking failed - http://43.167.223.118:8000 does not match any trusted origins.): /admin/login/

看样子是要配置 django 中的 setting.py，但是我在容器中没有找到对应的配置文件

**Comment by zhergd** [comment]
修改容器中/app/FasterRunner/settings的 base.py， 已经可以正常访问了
