### ISSUE TITLE
第一步搭建环境劝退很多人

### ISSUE THREAD

**Issue by Joytracy** [lihuacai168/AnotherFasterRunner#31]
第一步搭建环境劝退很多人，搭建文档好久也没更新了

**Comment by Joytracy** [comment]
搭建环境感觉老是出错

**Comment by lihuacai168** [comment]
> 第一步搭建环境劝退很多人，搭建文档好久也没更新了

docker-compose这个还是很简单的？
非docker的情况下，确实比较麻烦
