### ISSUE TITLE
删除api模板目录下面的api接口没有一起删除

### ISSUE THREAD

**Issue by huanjoyous** [lihuacai168/AnotherFasterRunner#43]
![image](https://user-images.githubusercontent.com/28851617/223608030-7cd97c3e-56c5-42e1-bef3-e0341aa62dd8.png)

**Comment by lihuacai168** [comment]
请把期望和实际描述清楚

**Comment by huanjoyous** [comment]
现象：web界面删除API 模板-文件夹节点，数据库api表（字段delete=0）没有删除
期望：web界面删除API 模板-文件夹节点，删除目录是否可以删除api接口。物理删除或者逻辑删除

**Comment by lihuacai168** [comment]
> 现象：web界面删除API 模板-文件夹节点，数据库api表（字段delete=0）没有删除 期望：web界面删除API 模板-文件夹节点，删除目录是否可以删除api接口。物理删除或者逻辑删除

也就是说，删除文件夹节点，要把这个文件夹下面所有的文件夹以及API都删除掉？

**Comment by huanjoyous** [comment]
> > wew：web界面api-api-文件文件夹节夹节，数据库api表表表（= 0）web：web界面界面界面界面界面界面界面界面界面界面-api模板-api模板模板文件文件夹节文件文件文件文件文件点文件
> 
> 也就是说，删除文件夹节点，要把这个文件夹下面所有的文件夹以及API都删除掉？

是的

**Comment by lihuacai168** [comment]
> > > wew：web界面api-api-文件文件夹节夹节，数据库api表表表（= 0）web：web界面界面界面界面界面界面界面界面界面界面-api模板-api模板模板文件文件夹节文件文件文件文件文件点文件
> > 
> > 
> > 也就是说，删除文件夹节点，要把这个文件夹下面所有的文件夹以及API都删除掉？
> 
> 是的

这样不是很好实现，要递归找出来所有的子节点，再把子节点对应的API全部都删除，并且一般来说，不希望删除数据，都是新建就好

**Comment by huanjoyous** [comment]
> > > > wew：web界面api api-api文件文件夹节夹节，api = 0（0）web：web界面界界面界界面界面界面界面界面界面界-api-api模板-api模板-api  -  api模板文件文件文件点文件
> > > 
> > > 
> > > 也就是说，删除文件夹节点，要把这个文件夹下面所有的文件夹以及API都删除掉？
> > 
> > 
> > 是的
> 
> 这样不是很好现实，要递归找出来所有的子节点，再把子节点对应的API全部删掉，而且而且一般来说，不希望删掉数据，都只是喼

现象操作：目录或者子目录下有api，当删除了其中一个目录，点击‘重置’按钮，会给显示出来
解决方案： 这种情况只能操作数据库删除了噢？
