### ISSUE TITLE
API模板-希望能添加批量添加参数的功能，类似yapi和postman

### ISSUE THREAD

**Issue by tahitimoon** [lihuacai168/AnotherFasterRunner#56]
当前问题：现在添加表单和params接口，如果参数有多个时，要一个个添加非常麻烦，如下图：
![image](https://user-images.githubusercontent.com/37645552/233332379-54c6d394-3372-4cf8-8f34-47583fb80f72.png)

期望：希望能添加批量参数的功能，如下图：
![image](https://user-images.githubusercontent.com/37645552/233332109-0f8ee240-d31e-4267-975c-a47f75c78bc0.png)

**Comment by lihuacai168** [comment]
#58
