### ISSUE TITLE
API模板-在列表界面和编辑界面，没有选择任何配置时，点击“运行API”，界面没有反应，接口会报500错误（参数是表单类型）

### ISSUE THREAD

**Issue by tahitimoon** [lihuacai168/AnotherFasterRunner#59]
![image](https://user-images.githubusercontent.com/37645552/233527397-df88f563-3825-43bc-bfa0-675a80d040e2.png)

![image](https://user-images.githubusercontent.com/37645552/233527600-6487a4b9-6866-4964-b5cd-70a69d61bd6b.png)

**Comment by lihuacai168** [comment]
这属于正常的报错，但不够友好
可以增加一些提示，如果没有选择配置，并且接口地址不是http开头的，就提示选择配置
