### ISSUE TITLE
配置管理-界面有多余元素显示

### ISSUE THREAD

**Issue by tahitimoon** [lihuacai168/AnotherFasterRunner#72]
如下图：
![image](https://user-images.githubusercontent.com/37645552/233828461-fc554401-dc30-4e4b-bb6f-29f2e2b4124b.png)

**Comment by tahitimoon** [comment]
在ConfigList组件中，<el-header>里面加一个overflow-x: hidden就好了，如下图
![image](https://user-images.githubusercontent.com/37645552/233829688-78523e8c-0e3c-41f4-b16e-64fce435a3ff.png)

**Comment by lihuacai168** [comment]
@tahitimoon #75
