### ISSUE TITLE
配置管理-添加驱动代码中已存在的hook函数，执行API时，提示request找不到

### ISSUE THREAD

**Issue by tahitimoon** [lihuacai168/AnotherFasterRunner#73]
问题描述：如下图，在配置管理里面添加前置${set_up($request)} ，然后在API模板中执行api，
![image](https://user-images.githubusercontent.com/37645552/233833531-b6ad06ec-56c6-4814-8bc9-e52312d4f73f.png)
![image](https://user-images.githubusercontent.com/37645552/233833635-947da4b7-c474-4571-a11e-d9de5dce1a52.png)
![image](https://user-images.githubusercontent.com/37645552/233833711-838c49e2-0956-4b3a-b912-3959991e63af.png)
疑问：配置管理里面的前置hook函数，不能找到接口里面的request吗？

**Comment by lihuacai168** [comment]
在配置里面用不了

**Comment by tahitimoon** [comment]
> 

那配置管理里面的前后置hook有什么用呀？

**Comment by tahitimoon** [comment]
> 在配置里面用不了

那配置管理里面的前后置hook有什么用呀？

**Comment by lihuacai168** [comment]
> > 在配置里面用不了
> 
> 那配置管理里面的前后置hook有什么用呀？

一开始想法一个通用的hook，用了这个配置的之后，API就会自动继承这个
貌似有点问题，还没细研究

**Comment by tahitimoon** [comment]
> > > 在配置里面用不了
> > 
> > 
> > 那配置管理里面的前后置hook有什么用呀？
> 
> 一开始想法一个通用的hook，用了这个配置的之后，API就会自动继承这个 貌似有点问题，还没细研究

通用的确实会方便很多，要不然每个api都要填写前置hook。这边的接口发送请求前，每次都会计算一下sign值，现在是拿前置hook处理的
