### ISSUE TITLE
服务部署后，您是怎么局域网访问的

### ISSUE THREAD

**Issue by sunny-xiabo** [lihuacai168/AnotherFasterRunner#8]

**Comment by lihuacai168** [comment]
https://www.yuque.com/lihuacai/sggdx7/kz9f2z
查看使用文档
![image](https://user-images.githubusercontent.com/11568297/156363087-43a1501a-5a12-4ce5-94f7-c828b9bf130b.png)

**Comment by lihuacai168** [comment]
如果使用docker-compose，前端build的话，是80端口。
前端dev模式是8080，

**Comment by sunny-xiabo** [comment]
找到原因了
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/71371027/156507478-cbbd87b6-952e-46ac-a69a-344cb13be747.png">
原来这里一直写的localhost:8000，前端Request URL:就一直显示，改了之后就可以局域网访问
