### ISSUE TITLE
pip install -r .\requirements.txt报错

### ISSUE THREAD

**Issue by hy546880109** [lihuacai168/AnotherFasterRunner#80]
python3.9.7安装时报错
![image](https://user-images.githubusercontent.com/44777854/233950013-bfa3b55a-2033-4049-9c35-789a43a92103.png)

**Comment by lihuacai168** [comment]
pip -V
python -V
看看版本和路径

这看上去似乎和编码有点问题
把powershell换成cmd看看
安装的时候，最好就上国内的源，会更快点

**Comment by hy546880109** [comment]
cmd也报错，已经换了国内源了
<img width="502" alt="image" src="https://user-images.githubusercontent.com/44777854/234001775-7d95ef1b-c733-4725-8273-6df7e278ec5b.png">

**Comment by hy546880109** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/44777854/234001900-cafb651c-1605-4ef6-b559-8f11566c79eb.png">

**Comment by lihuacai168** [comment]
直接pip install six
随便安装一个包试试呢

**Comment by hy546880109** [comment]
![image](https://user-images.githubusercontent.com/44777854/234148983-e3d724dd-b582-4739-9611-d694d6d1f787.png)
单个可以

**Comment by hy546880109** [comment]
通过这个方法解决了，原来是系统的问题
![image](https://user-images.githubusercontent.com/44777854/234151773-90a9cfb9-c66e-4f17-b39b-fa12f02f5804.png)
