### ISSUE TITLE
Extract 这个功能在报告中好像不显示了，使用文档是有的

### ISSUE THREAD

**Issue by thb-club** [lihuacai168/AnotherFasterRunner#93]
![image](https://user-images.githubusercontent.com/51936990/236793677-2b1ccb09-ff77-4abe-8a82-a4d30e7ba9e5.png)

**Comment by lihuacai168** [comment]
之前的实现方案有性能问题，大json会卡主
改成点击content的具体字段，就会自动复制
例如，点击code，就自动复制了取值路径

文档的具体链接是哪个，我改一下
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/11568297/236794131-96581866-f106-4222-8fce-e5f4ee7794b7.png">

**Comment by thb-club** [comment]
不是这个复制问题，  是说这个字段显示的内容没了
![image](https://user-images.githubusercontent.com/51936990/236794989-45af3ad7-1070-4a6e-9d4f-24ae88835a0a.png)

**Comment by thb-club** [comment]
https://www.yuque.com/lihuacai/fasterunner/lx2r93

**Comment by lihuacai168** [comment]
> 看代码中是没有这个提取字段的信息展示了 我现在想加一下 因为目前没这个字段 不知道看是否提取成功

这里是为了生成jsonpath给用户复制用的，不是显示用户用了几个extract。
如果提取不成功，会报错，显示异常
