### ISSUE TITLE
定时任务和异步任务

### ISSUE THREAD

**Issue by Allrivers-maker** [lihuacai168/AnotherFasterRunner#97]
**描述问题**
定时任务和和手动执行没有效果

**重现步骤**
重现行为的步骤：
1. 前往定时任务页面
2. 点击定时任务某一行的后面手动执行按钮
3. 返回信息用例执行中，稍后查看结果
4. 等几十分钟报告也没有出来

**期望的行为**
想知道定时任务和异步执行的报告 是在报告列表中展现的么

**版本和代码（请填写以下信息）：**
https://fast.huacai.one/fastrunner/login

**Comment by lihuacai168** [comment]
在项目根目录执行make ps，查看mq，celery-beat和celery-worker状态是否正常
看看celery-beat和celery-worker，make logs可以看到

**Comment by thb-club** [comment]
我本地windows能看到么  想执行celery-worker一直开不了

**Comment by lihuacai168** [comment]
<img width="969" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/11568297/7b85c4a9-ab23-4666-88fe-5629081b7d1c">
异步和定时报告，需要关闭只看自己

**Comment by lihuacai168** [comment]
> 我本地windows能看到么 想执行celery-worker一直开不了

异步和定时任务，需要mq，celery-beat和celery-worker

**Comment by thb-club** [comment]
我们这里自己部署的线上是有这些docker开启的

**Comment by lihuacai168** [comment]
> 

那线上的定时任务是否正常?
不正常就提供我上面说的日志

**Comment by lihuacai168** [comment]
<img width="1778" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/11568297/475b66c1-8858-4a11-9b7d-0ad0065af8dd">
我看演示demo是有报告的，不知道是不是你操作的

**Comment by thb-club** [comment]
是的 我刚刚操作的

**Comment by thb-club** [comment]
rabbitmq线上需要配置什么host么 还是不动  直接启动容器就行

**Comment by lihuacai168** [comment]
> rabbitmq线上需要配置什么host么 还是不动 直接启动容器就行

不需要，可以看快速启动的文档，先启动来验证。
环境变量后面在自己修改一下就好

**Comment by thb-club** [comment]
python -m celery -A FasterRunner.mycelery worker -l info --concurrency=4 
windows运行这个报错
EOFError: Ran out of input

**Comment by thb-club** [comment]
定时任务没执行是不是因为 时间保存的格式 是 UTC

**Comment by lihuacai168** [comment]
> 定时任务没执行是不是因为 时间保存的格式 是 UTC

有可能，可以用在线demo验证一下

**Comment by thb-club** [comment]
在线demo没有效果

**Comment by lihuacai168** [comment]
> 

没效果指的是不能复现？还是不能使用

**Comment by thb-club** [comment]
定时任务没运行

**Comment by lihuacai168** [comment]
是跟utc时间有关系。。
这里改成3，也就是相当于北京时间的11点，就能正常触发，改成11，就不能触发。
<img width="937" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/11568297/346e7207-858c-4bf7-a9f7-2ae51c6976c9">

**Comment by thb-club** [comment]
我改成每2分钟一次好像不执行

**Comment by thb-club** [comment]
celery 和rabbitmq连上了  但是触发worker能收到消息 不能消费

**Comment by lihuacai168** [comment]
> 我改成每2分钟一次好像不执行

没问题的，在线demo你可以看看

**Comment by thb-club** [comment]
我这边看部署的是我把worker容器进程关了  rabbitmq队列中是有消息堆积的  就是worker这里打开会接收消费 但是不执行方法有点奇怪

**Comment by thb-club** [comment]
想问下大佬 你的linux线上环境是多少版本的 我这边是5.1.4

**Comment by lihuacai168** [comment]
> 

如果你没改过代码，正常是会消费的

**Comment by lihuacai168** [comment]
> 

你真的是什么版本

**Comment by thb-club** [comment]
> > 
> 
> 如果你没改过代码，正常是会消费的

没改过 就用的你docker部署搞的

**Comment by thb-club** [comment]
会不会与linux版本有关系  worker拿到任务了 没有执行异步方法

**Comment by lihuacai168** [comment]
> 

worker运行在docker里面，没关系的

**Comment by thb-club** [comment]
这样你知道咋回事么   大佬  worker日志一直是i这样 接收消息不执行
![image](https://github.com/lihuacai168/AnotherFasterRunner/assets/51936990/79d40f94-6f8a-4438-838f-5d6e59fddc34)

**Comment by thb-club** [comment]
大佬 帮忙看看这个问题

**Comment by lihuacai168** [comment]
> 大佬 帮忙看看这个问题

抱歉，目前提供的内容，我无法帮你解答
