### ISSUE TITLE
安装 python 库遇到的问题汇总

### ISSUE THREAD

**Issue by abeelan** [lihuacai168/AnotherFasterRunner#98]
**版本和代码**
- 操作系统：macOs 11.5.1
- Python版本: Python 3.9.15

#### 问题：安装 `anyjson` 库时出现报错。
```shell
$ pip install -r requirements.txt  
...
Collecting anyjson
  Downloading http://pypi.doubanio.com/packages/c3/4d/d4089e1a3dd25b46bebdb55a992b0797cff657b4477bc32ce28038fdecbc/anyjson-0.3.3.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in anyjson setup command: use_2to3 is invalid.
      [end of output]
```

解决：[参考地址](https://stackoverflow.com/questions/72414481/error-in-anyjson-setup-command-use-2to3-is-invalid)
```shell
$ pip install "setuptools<58.0.0"
```

#### 问题：安装 `django-simpleui ` 库时出现报错。
解决：添加 `--upgrade` 参数
```shell
$ pip install --upgrade django-simpleui 
```

**Comment by lihuacai168** [comment]
这不科学啊，已经限定了setuptool是版本啦

<img width="758" alt="image" src="https://github.com/lihuacai168/AnotherFasterRunner/assets/11568297/2d74e57b-6c6e-441a-b7b5-a9309c1599f0">

**Comment by abeelan** [comment]
我是新建的虚拟环境安装依赖的~ 具体就不清楚啥原因了~ 这里做个记录。

**Comment by lihuacai168** [comment]
> **版本和代码**
> 
> * 操作系统：MacOs 15
> * Python版本: Python 3.9
> 
> ### 拉取代码，本地部署，遇到的一些问题。
> #### 问题：安装 `anyjson` 库时出现报错。
> ```shell
> $ pip install -r requirements.txt  
> ...
> Collecting anyjson
>   Downloading http://pypi.doubanio.com/packages/c3/4d/d4089e1a3dd25b46bebdb55a992b0797cff657b4477bc32ce28038fdecbc/anyjson-0.3.3.tar.gz (8.3 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [1 lines of output]
>       error in anyjson setup command: use_2to3 is invalid.
>       [end of output]
> ```
> 
> 解决：[参考地址](https://stackoverflow.com/questions/72414481/error-in-anyjson-setup-command-use-2to3-is-invalid)
> 
> ```shell
> $ pip install "setuptools<58.0.0"
> ```
> 
> #### 问题：安装 `django-simpleui ` 库时出现报错。
> 解决：添加 `--upgrade` 参数
> 
> ```shell
> $ pip install --upgrade django-simpleui 
> ```

macOS有15版本？是不是写错了，python3.9，具体版本麻烦也补充一下

**Comment by abeelan** [comment]
确实是我的疏忽，已更新。
